<?php
/**
 * @file
 * Main module file.
 *
 * @ingroup loft_deploy_ip Loft Deploy IP Access
 * @{
 */

define('LOFT_DEPLOY_IP_FILTER', 'exclude');

/**
 * Implements hook_loft_deploy_border_access().
 */
function loft_deploy_ip_loft_deploy_border_access_alter(&$access, $site_role, $cookie) {
  $config = \Drupal::config('loft_deploy_ip.settings');
  $filter_mode = $config->get('filter_mode');
  $access = $filter_mode === 'include' ? FALSE : TRUE;
  if (($ips = $config->get('ip_list'))) {
    foreach ($ips as $ip) {
      if (\Drupal::request()->getClientIp() == trim($ip)) {
        $access = $filter_mode === 'include' ? TRUE : FALSE;
        break;
      }
    }
  }
  $access = empty($cookie) && $access;
}

/**
 * Implements hook_menu().
 */
function loft_deploy_ip_menu() {
  $items = [];
  $items['admin/config/development/loft-deploy'] = [
    'title' => 'Loft Deploy Access',
    'description' => 'Hide or show the border based on IP address(es).',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['loft_deploy_ip_admin_settings'],
    'access arguments' => ['loft_deploy_ip:administer'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'loft_deploy_ip.admin.inc',
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function loft_deploy_ip_permission() {
  return [
    'loft_deploy_ip:administer' => [
      'title' => t('Administer Loft Deploy IP Access'),
      'description' => t('Perform administration tasks for Loft Deploy IP Access.'),
      'restrict access' => FALSE,
    ],
  ];
}
